# Base URL
@baseUrl = http://localhost:3000/jobs

### 1. Get All Todos
GET {{baseUrl}}

### 2. Get a Single Todo by ID
GET {{baseUrl}}/1

### 3. Create a New Todo
POST {{baseUrl}}
Content-Type: application/json

{
			"id": 7,
			"title": "React Native Developer",
			"type": "Full-Time",
			"description": "Join our team as a Front-End Developer in beautiful Portland, OR. We are looking for a skilled and enthusiastic individual to help us create innovative web solutions. Competitive salary and great benefits package available.",
			"location": "Portland, OR",
			"salary": "$100K - $110K",
			"company": {
				"name": "Port Solutions INC",
				"description": "Port Solutions is a leading technology company specializing in software development and digital marketing. We are committed to providing our clients with cutting-edge solutions and our employees with a supportive and rewarding work environment.",
				"contactEmail": "contact@ipsumlorem.com",
				"contactPhone": "555-555-5555"
	}
}

### 4. Update an Existing Todo
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "title": "Learn Vuex - Updated",
  "completed": true
}

### 5. Delete a Todo
DELETE {{baseUrl}}/1
